<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="7" passed="5">
  <reporter-output>
    <line>
      <![CDATA[Hi--6]]>
    </line>
    <line>
      <![CDATA[Hi--4]]>
    </line>
    <line>
      <![CDATA[Hi--1]]>
    </line>
    <line>
      <![CDATA[Hi--3]]>
    </line>
    <line>
      <![CDATA[Hi--5]]>
    </line>
    <line>
      <![CDATA[Hi--7]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="209" started-at="2021-02-04T15:39:27 IST" finished-at="2021-02-04T15:39:28 IST">
    <groups>
      <group name="functional">
        <method signature="Demo4.tc3()[pri:0, instance:demo.Testng.Demo.qsp.Demo4@32709393]" name="tc3" class="demo.Testng.Demo.qsp.Demo4"/>
        <method signature="Demo4.tc5()[pri:0, instance:demo.Testng.Demo.qsp.Demo4@32709393]" name="tc5" class="demo.Testng.Demo.qsp.Demo4"/>
        <method signature="Demo4.tc7()[pri:0, instance:demo.Testng.Demo.qsp.Demo4@32709393]" name="tc7" class="demo.Testng.Demo.qsp.Demo4"/>
      </group> <!-- functional -->
      <group name="Regression">
        <method signature="Demo4.tc2()[pri:0, instance:demo.Testng.Demo.qsp.Demo4@32709393]" name="tc2" class="demo.Testng.Demo.qsp.Demo4"/>
      </group> <!-- Regression -->
      <group name="smoke">
        <method signature="Demo4.tc1()[pri:3, instance:demo.Testng.Demo.qsp.Demo4@32709393]" name="tc1" class="demo.Testng.Demo.qsp.Demo4"/>
        <method signature="Demo4.tc4()[pri:2, instance:demo.Testng.Demo.qsp.Demo4@32709393]" name="tc4" class="demo.Testng.Demo.qsp.Demo4"/>
        <method signature="Demo4.tc6()[pri:1, instance:demo.Testng.Demo.qsp.Demo4@32709393]" name="tc6" class="demo.Testng.Demo.qsp.Demo4"/>
      </group> <!-- smoke -->
    </groups>
    <test name="Default test" duration-ms="209" started-at="2021-02-04T15:39:27 IST" finished-at="2021-02-04T15:39:28 IST">
      <class name="demo.Testng.Demo.qsp.Demo4">
        <test-method status="PASS" signature="tc6()[pri:1, instance:demo.Testng.Demo.qsp.Demo4@32709393]" name="tc6" duration-ms="32" started-at="2021-02-04T15:39:27 IST" finished-at="2021-02-04T15:39:28 IST">
          <reporter-output>
            <line>
              <![CDATA[Hi--6]]>
            </line>
          </reporter-output>
        </test-method> <!-- tc6 -->
        <test-method status="PASS" signature="tc4()[pri:2, instance:demo.Testng.Demo.qsp.Demo4@32709393]" name="tc4" duration-ms="5" started-at="2021-02-04T15:39:28 IST" finished-at="2021-02-04T15:39:28 IST">
          <reporter-output>
            <line>
              <![CDATA[Hi--4]]>
            </line>
          </reporter-output>
        </test-method> <!-- tc4 -->
        <test-method status="PASS" signature="tc1()[pri:3, instance:demo.Testng.Demo.qsp.Demo4@32709393]" name="tc1" duration-ms="3" started-at="2021-02-04T15:39:28 IST" finished-at="2021-02-04T15:39:28 IST">
          <reporter-output>
            <line>
              <![CDATA[Hi--1]]>
            </line>
          </reporter-output>
        </test-method> <!-- tc1 -->
        <test-method status="FAIL" signature="tc3()[pri:0, instance:demo.Testng.Demo.qsp.Demo4@32709393]" name="tc3" duration-ms="9" depends-on-groups="smoke" started-at="2021-02-04T15:39:28 IST" finished-at="2021-02-04T15:39:28 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at demo.Testng.Demo.qsp.Demo4.tc3(Demo4.java:19)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Hi--3]]>
            </line>
          </reporter-output>
        </test-method> <!-- tc3 -->
        <test-method status="PASS" signature="tc5()[pri:0, instance:demo.Testng.Demo.qsp.Demo4@32709393]" name="tc5" duration-ms="4" depends-on-groups="smoke" started-at="2021-02-04T15:39:28 IST" finished-at="2021-02-04T15:39:28 IST">
          <reporter-output>
            <line>
              <![CDATA[Hi--5]]>
            </line>
          </reporter-output>
        </test-method> <!-- tc5 -->
        <test-method status="PASS" signature="tc7()[pri:0, instance:demo.Testng.Demo.qsp.Demo4@32709393]" name="tc7" duration-ms="3" depends-on-groups="smoke" started-at="2021-02-04T15:39:28 IST" finished-at="2021-02-04T15:39:28 IST">
          <reporter-output>
            <line>
              <![CDATA[Hi--7]]>
            </line>
          </reporter-output>
        </test-method> <!-- tc7 -->
        <test-method status="SKIP" signature="tc2()[pri:0, instance:demo.Testng.Demo.qsp.Demo4@32709393]" name="tc2" duration-ms="0" depends-on-groups="functional" started-at="2021-02-04T15:39:28 IST" finished-at="2021-02-04T15:39:28 IST">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Demo4.tc2()[pri:0, instance:demo.Testng.Demo.qsp.Demo4@32709393] depends on not successfully finished methods in group "functional"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Demo4.tc2()[pri:0, instance:demo.Testng.Demo.qsp.Demo4@32709393] depends on not successfully finished methods in group "functional"
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc2 -->
      </class> <!-- demo.Testng.Demo.qsp.Demo4 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
